### ISSUE TITLE
all menu

### ISSUE THREAD

**Issue by kittisak0501** [auto0032/STEAK#4]
continue in the `appetizer menu` branch `feture-others-menu` use the` appetizer-menu.ejs` as base and modified it to create `main-dish.ejs` ,`dessert-menu.ejs` and `drinks-menu.ejs`
f78c7a1f04decf4d6efd034242190923bc376a29

**Comment by auto0032** [comment]
f78c7a1f04decf4d6efd034242190923bc376a29
